import { fonts, makeStyles } from "../../theme";

export const useStyles = makeStyles((colors) => ({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  ageGateContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  ageGateTitle: {
    fontSize: 32,
    fontFamily: fonts.headline,
    color: colors.headline,
    letterSpacing: 0.5,
  },
  ageGateSubtitle: {
    fontSize: 14,
    fontFamily: fonts.body,
    color: colors.body,
    marginTop: 6,
  },
  divider: {
    width: 60,
    height: 2,
    backgroundColor: colors.border,
    marginVertical: 28,
  },
  ageGateBody: {
    color: colors.body,
    fontFamily: fonts.body,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 14,
  },
  confirmBtn: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 28,
    paddingVertical: 14,
    marginTop: 24,
  },
  confirmText: {
    color: colors.background,
    fontFamily: fonts.labelBold,
    fontSize: 15,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  headerTitle: {
    color: colors.primary,
    fontFamily: fonts.label,
    fontSize: 13,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  dotsContainer: {
    flexDirection: "row",
    gap: 8,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: colors.muted,
    opacity: 0.4,
  },
  dotActive: {
    backgroundColor: colors.primary,
    opacity: 1,
  },
  pager: {
    flex: 1,
  },
  page: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 36,
    paddingVertical: 20,
  },
  iconRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  pageTitle: {
    color: colors.headline,
    fontFamily: fonts.headline,
    fontSize: 24,
    marginTop: 20,
    textAlign: "center",
  },
  pagesDivider: {
    width: 44,
    height: 2,
    backgroundColor: colors.border,
    marginVertical: 18,
  },
  pageBody: {
    color: colors.body,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    marginBottom: 12,
  },
  footnote: {
    color: colors.muted,
    fontFamily: fonts.label,
    fontSize: 10,
    letterSpacing: 0.5,
    textAlign: "center",
    paddingTop: 14,
    paddingBottom: 10,
  },
  getStartedBtn: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingHorizontal: 28,
    paddingVertical: 14,
    marginTop: 24,
  },
  getStartedText: {
    color: colors.background,
    fontFamily: fonts.labelBold,
    fontSize: 15,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
}));
